# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: $GITHUB_WORKSPACE/ci/linux/install-dependencies-ubuntu.sh

      # Runs a set of commands using the runners shell
      - name: Build
        run: $GITHUB_WORKSPACE/ci/linux/build-ubuntu.sh
        
      - name : Package
        run: $GITHUB_WORKSPACE/ci/linux/package-ubuntu.sh
        
      - name : Publish artifact
        uses: actions/upload-artifact@v2.2.3
        with: 
          path: ./package
          name: Built package
      - name : Publish blender file to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{github.workspace}}/transition.blend
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{github.ref}}

      - name : Publish binary file
        if: github.event_name == 'release'
        uses: Roang-zero1/github-upload-release-artifacts-action@v2.1.0
        with:
          args: '${{github.workspace}}/package'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
        
